version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js version 12..."
      - n 12 && rm -rf /tmp/*
  build:
    commands:
      - echo "Building application..."
      - aws s3 cp index.html s3://csce412jjoseph.xyz/ --content-type "text/html"
  post_build:
    commands:
      - echo "Build completed"
