version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - aws s3 cp index.html s3://your-bucket-name/ --content-type "text/html"
      - aws s3 cp styles.css s3://your-bucket-name/ --content-type "text/css"
      - aws s3 cp script.js s3://your-bucket-name/ --content-type "application/javascript"
      # Add more commands for other files as needed

artifacts:
  files:
    - '**/*'
